keycloak_security_login:
    path:             /login
    defaults:         { _controller: KeycloakClientBundle:Security:login}

keycloak_security_logout:
    path:             /logout
    defaults:         { _controller: KeycloakClientBundle:Security:logout}
