services:
    Micayael\Keycloak\ClientBundle\Security\User\AuthenticatorUserProvider: ~

    Micayael\Keycloak\ClientBundle\Security\LoginFormAuthenticator:
        arguments: ['@form.factory', '@router', '%keycloak_client_config%']
